from django.contrib import admin
from app.models import *
# Register your models here.
admin.site.register(Blog)
# admin.site.register(BlogComments)
admin.site.register(ContactUs)
admin.site.register(HomePageStatistics1)
admin.site.register(HomePageStatistics2)
admin.site.register(HomePageStatistics3)
admin.site.register(HomePageStatistics4)
admin.site.register(freegcategory)
admin.site.register(pricingplan)
admin.site.register(pricingplanrow)
admin.site.register(pricingplanvalue)
admin.site.register(Testimonial)
admin.site.register(Team)
admin.site.register(FreegInfo)
admin.site.register(Stepshomepage)
admin.site.register(Largebackgroundimage)
admin.site.register(Casestudy)
admin.site.register(HomePageCaseStudy)
admin.site.register(Freegheadquaters)
admin.site.register(ContactPageCaseStudy)
admin.site.register(BestClinetsImages)
admin.site.register(HowFreegCanHelp)
admin.site.register(Careers)
admin.site.register(FormSuccess)
admin.site.register(StaticBlogImages)