from django.contrib import admin
from app.models import *
# Register your models here.
# admin.site.register(Blog)
# admin.site.register(BlogComments)
admin.site.register(ContactUs)
admin.site.register(HomePageStatistics1)
admin.site.register(HomePageStatistics2)
admin.site.register(HomePageStatistics3)
admin.site.register(HomePageStatistics4)
admin.site.register(freegcategory)
# admin.site.register(pricingplan)
# admin.site.register(pricingplanrow)
# admin.site.register(pricingplanvalue)
admin.site.register(CaseStudyParagraph)
admin.site.register(Testimonial)
admin.site.register(Team)
admin.site.register(FreegInfo)
admin.site.register(Contact_Form_Success_Steps)
admin.site.register(HomePagebackgroundimage)
admin.site.register(Casestudy)
admin.site.register(HomePageCaseStudy)
admin.site.register(Freegheadquaters)
admin.site.register(ContactPageCaseStudy)
admin.site.register(BestClinetsImages)
admin.site.register(HowFreegCanHelp)
admin.site.register(Careers)
# admin.site.register(FormSuccess)
# admin.site.register(StaticBlogImages)
admin.site.register(BranchOffices)
admin.site.register(Responsibilty)
admin.site.register(Requirement)
admin.site.register(PerksBenefit)
admin.site.register(CareerForm)
admin.site.register(ChannelPartners)
admin.site.register(MoreCategories)
admin.site.register(CareerOtherForm)
admin.site.register(MoreCategorySubCategory)
admin.site.register(HomePageMainHeading)
admin.site.register(Query)
admin.site.register(AboutUs_How_We_Started)
admin.site.register(AboutUs_Our_Vision)
admin.site.register(AboutUs_What_We_Do)
admin.site.register(BackGroundImage_NavigationBar)
admin.site.register(CareerSubheading)
admin.site.register(WebsiteTitles)
admin.site.register(MetaDataSingle)
admin.site.register(MetaDataAll)
admin.site.register(MetaDataFreeGCategory)
admin.site.register(MetaDataCaseStudy)
admin.site.register(MetaDataBlog)
admin.site.register(CaseStudyVisibility)




